CHUNKS_URLS = [
'https://drive.google.com/uc?export=download&id=1G1JDuDiteXjOsOFQCVT9l1SmbqDAH5aC', #CHUNK 1
'https://drive.google.com/uc?export=download&id=1Bsz0QHq1jnMN2z0ZVLooPqDej6BGgSNz', #CHUNK 2
'https://drive.google.com/uc?export=download&id=1XPuq62pFCzvGsec6JdsQfQcTqoKejwk4', #CHUNK 3
'https://drive.google.com/uc?export=download&id=1hZNjgOlW8Th3PYlpAdYfp3940NyGkYHb', #CHUNK 4
'https://drive.google.com/uc?export=download&id=1AqRsyXgdSrUbgChkmhsnMh7tA9bxLgvD', #CHUNK 5
'https://drive.google.com/uc?export=download&id=1Any3lUDOLhO0m6EC-Nvdg6lD9FErDP02', #CHUNK 6
'https://drive.google.com/uc?export=download&id=1XgQk-rsgcncrE4_J3Cm3GrKsgMOWge54', #CHUNK 7
'https://drive.google.com/uc?export=download&id=1SxQumabGPCzXQGtpYythZQ0hFDbkDG50', #CHUNK 8
'https://drive.google.com/uc?export=download&id=1fluYgD4GMcJZpkxD8JKihq9Sfg3OOyDm', #CHUNK 9
'https://drive.google.com/uc?export=download&id=1VMKrcsY6sJcX3BPisQM-mu4gXm3UG1bM', #CHUNK 10
'https://drive.google.com/uc?export=download&id=1-RE2kohe3M8zPFwR7CSxykeLyOcr158A', #CHUNK 11
'https://drive.google.com/uc?export=download&id=1Ob4hOfGPQTqqhbF2VC1Vw5q5CN42ULLt', #CHUNK 12
'https://drive.google.com/uc?export=download&id=1bmebmDinEGuAPJX3YWA90aHJYXkgtXrM', #CHUNK 13
'https://drive.google.com/uc?export=download&id=1HPMJk1RZoXOLTgS5fRFyPnuRDXGflyCA', #CHUNK 14
'https://drive.google.com/uc?export=download&id=11whVkPbB0wve7Vih6RKHBd4liPHEZKy1', #CHUNK 15
'https://drive.google.com/uc?export=download&id=1GU9L-mfEsmhGZ_YTx86khRsZiYWMrc3s', #CHUNK 16
'https://drive.google.com/uc?export=download&id=1BMSyPBKCsFSPjNgikXAhVsSUV61YRaCJ', #CHUNK 17
'https://drive.google.com/uc?export=download&id=17H4MQwDwbOubEnMHKY4RcRxgCdiyDskZ', #CHUNK 18
'https://drive.google.com/uc?export=download&id=1v7tQ8oGPb3pxA9t3nF7iugLi8IVn1flL', #CHUNK 19
'https://drive.google.com/uc?export=download&id=1kgyP40hREAOle9TSARNO7JO81FbCtukO', #CHUNK 20
'https://drive.google.com/uc?export=download&id=136Kv3w9qe2jOQJNJRYitj9-DFAwY0nJd', #CHUNK 21
'https://drive.google.com/uc?export=download&id=1P0ssKR9MO4NhHvGp6dC4tMLPd-G1VxSa', #CHUNK 22
'https://drive.google.com/uc?export=download&id=1PoeVt4nsnk04sE0yJq5ulovHCTJzFjp_', #CHUNK 23
'https://drive.google.com/uc?export=download&id=17dIx02U1NGecDdhNswaOyFqJ4pk2vUVL', #CHUNK 24
'https://drive.google.com/uc?export=download&id=1kG2-c_BG5JuFJmj6O2ruQ6-BcsdDDcDY', #CHUNK 25
'https://drive.google.com/uc?export=download&id=1C_FkrnnIp51h4U9zn1VnZ7J5CT_K_DbK', #CHUNK 26
'https://drive.google.com/uc?export=download&id=1IBz-JtCQEU5x2GXc2SFhkT2tT0_jo1mV', #CHUNK 27
'https://drive.google.com/uc?export=download&id=1-5moNLRJNza0htUBZnnnpzs67I5Qu14c', #CHUNK 28
'https://drive.google.com/uc?export=download&id=1dW9lN94NyNAQZKstZiSfqI7_zpo-qIkN', #CHUNK 29
'https://drive.google.com/uc?export=download&id=1sR-RH3rAk-E2rQVb8qVmd3aUWDEkapiB', #CHUNK 30
'https://drive.google.com/uc?export=download&id=1uSnOaaij0G6GsbVWFvHgpu7MkMxJxCEJ', #CHUNK 31
'https://drive.google.com/uc?export=download&id=1eNclGY6lP3JTDLaZzShY3OGWIeetevwF', #CHUNK 32
'https://drive.google.com/uc?export=download&id=1epWisbAE9wUj2Wxc-odLleb77IfHBhi6', #CHUNK 33
'https://drive.google.com/uc?export=download&id=1LkwJgz3OcV2TOKiR5obRC644CBJhMvmD', #CHUNK 34
'https://drive.google.com/uc?export=download&id=1LuikvNNvGML4vIaV0xoYv-x-r4FejED3', #CHUNK 35
'https://drive.google.com/uc?export=download&id=1f07mrJ1CwgFPt1VX1D64guFyGONFWfKe', #CHUNK 36
'https://drive.google.com/uc?export=download&id=18bTZuG47kY50b-tE174T0aaaUiU31GW2', #CHUNK 37
'https://drive.google.com/uc?export=download&id=1j9t1xk5_8wFG07Omsc2WO1p-1oQFxGy3', #CHUNK 38
'https://drive.google.com/uc?export=download&id=1e6Xh3sBxmytIqLM9x_lkBXw_F5Yw5Apk', #CHUNK 39
'https://drive.google.com/uc?export=download&id=1xbPiIIImlrfzkGqcct9_ZSNw21JGh3kp', #CHUNK 40
'https://drive.google.com/uc?export=download&id=1E9S6gOKcCZ9d03cswzzOzd0Va3Ks2VVk', #CHUNK 41
'https://drive.google.com/uc?export=download&id=1gPoWrklCRwvPK6BOPsfGvorvZsGddzK2', #CHUNK 42
'https://drive.google.com/uc?export=download&id=1OsFvafw03zhbJ-0oXClUfZ3g3HiYUb2V', #CHUNK 43
'https://drive.google.com/uc?export=download&id=1oB2ZiOCCmd54kDRGNa-TwpkAAOrAL5tb', #CHUNK 44
'https://drive.google.com/uc?export=download&id=1bXm-RdszcQR3qteymEgocxHHccjNHD7I', #CHUNK 45
'https://drive.google.com/uc?export=download&id=1N1cCaL7t2-Ta9ybKw1WjessdHWqoLBq1', #CHUNK 46
'https://drive.google.com/uc?export=download&id=1a3DStc2PsOfY9-f82hZVIy8uefTaJMkG', #CHUNK 47
'https://drive.google.com/uc?export=download&id=1V3goJ8v_ULvsxL8CvyCUGeHVD8y_la-l', #CHUNK 48
'https://drive.google.com/uc?export=download&id=1xYbDRpTUhlKR1rqXQmXmzb8wICbAi8tQ', #CHUNK 49
'https://drive.google.com/uc?export=download&id=1okGWxD5c0torQR2oV8m5Np4hvt9zzAeb', #CHUNK 50
'https://drive.google.com/uc?export=download&id=1cMEZnLDuQdoKJMYtCGbdwJBPUU224TIE', #CHUNK 51
'https://drive.google.com/uc?export=download&id=1T9aLjdhB7Dqvb2Q7se16HLxvQslb0aBP', #CHUNK 52
'https://drive.google.com/uc?export=download&id=1BW-AE9YzYYcW0qkyQ0n0phl3dn6CDNWZ', #CHUNK 53
'https://drive.google.com/uc?export=download&id=1QI-9-h1ssJZkxj0mGb_YkHyhOgEan7k4', #CHUNK 54
'https://drive.google.com/uc?export=download&id=1Iv6M9b-z4YEJLRwUNjvrYcs0IHWPLrMg', #CHUNK 55
'https://drive.google.com/uc?export=download&id=1eUn7XEO3RtuMF3rde0u-TPTF9mthtWH5', #CHUNK 56
'https://drive.google.com/uc?export=download&id=1W7UaCwd2lnh88Vyg8BX8WZNtGeyKCaNz', #CHUNK 57
'https://drive.google.com/uc?export=download&id=1UgKLw28lw8fqK0OfOqaZ-LlP9GV0EUnM', #CHUNK 58
'https://drive.google.com/uc?export=download&id=1lLjy9fs6V6KwcbKS-BFQadLU_9TIgjJG', #CHUNK 59
'https://drive.google.com/uc?export=download&id=1Xh0LhQzfX2y6p7M9AqnhKrdtxdDPz_7P' #CHUNK 60
]